const LayoutActionTypes = {
  OPEN_SNACKBAR: 'OPEN_SNACKBAR',
  CLOSE_SNACKBAR: 'CLOSE_SNACKBAR',
  SET_SNACKBAR_MESSAGE: 'SET_SNACKBAR_MESSAGE',
  SET_SNACKBAR_VARIANT: 'SET_SNACKBAR_VARIANT',
};

export default LayoutActionTypes;
