const ConversationActionTypes = {
  FETCH_CONVERATIONS_START: 'FETCH_CONVERATIONS_START',
  FETCH_CONVERATIONS_SUCCESS: 'FETCH_CONVERATIONS_SUCCESS',
  FETCH_CONVERATIONS_FAILURE: 'FETCH_CONVERATIONS_FAILURE',
};

export default ConversationActionTypes;
