const ConversationActionTypes = {
  FETCH_CONVERATIONS_START: 'FETCH_CONVERATIONS_START',
  FETCH_CONVERATIONS_SUCCESS: 'FETCH_CONVERATIONS_SUCCESS',
  FETCH_CONVERATIONS_FAILURE: 'FETCH_CONVERATIONS_FAILURE',
  SEND_MESSAGE_START: 'SEND_MESSAGE_START',
  SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
  SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE',
  SETUP_NEW_CONVERSATION_START: 'SETUP_NEW_CONVERSATION_START',
  SETUP_NEW_CONVERSATION_SUCCESS: 'SETUP_NEW_CONVERSATION_SUCCESS',
  SETUP_NEW_CONVERSATION_FAILURE: 'SETUP_NEW_CONVERSATION_FAILURE',
  SET_CONVERSATION_TO_READ: 'SET_CONVERSATION_TO_READ',
};

export default ConversationActionTypes;
