const ApplicationTypes = {
  FETCH_ALL_APPLICATIONS_START: 'FETCH_ALL_APPLICATIONS_START',
  FETCH_ALL_APPLICATIONS_SUCCESS: 'FETCH_ALL_APPLICATIONS_SUCCESS',
  FETCH_ALL_APPLICATIONS_FAILURE: 'FETCH_ALL_APPLICATIONS_FAILURE',
  ACCEPT_APPLICATION_START: 'ACCEPT_APPLICATION_START',
  ACCEPT_APPLICATION_SUCCESS: 'ACCEPT_APPLICATION_SUCCESS',
  ACCEPT_APPLICATION_FAILURE: 'ACCEPT_APPLICATION_FAILURE',
  DECLINE_APPLICATION_START: 'DECLINE_APPLICATION_START',
  DECLINE_APPLICATION_SUCCESS: 'DECLINE_APPLICATION_SUCCESS',
  DECLINE_APPLICATION_FAILURE: 'DECLINE_APPLICATION_FAILURE',
  SEND_APPLICATION_START: 'SEND_APPLICATION_START',
  SEND_APPLICATION_SUCCESS: 'SEND_APPLICATION_SUCCESS',
  SEND_APPLICATION_FAILURE: 'SEND_APPLICATION_FAILURE',
};

export default ApplicationTypes;
