const ApplicationTypes = {
  FETCH_ALL_APPLICATIONS_START: 'FETCH_ALL_APPLICATIONS_START',
  FETCH_ALL_APPLICATIONS_SUCCESS: 'FETCH_ALL_APPLICATIONS_SUCCESS',
  FETCH_ALL_APPLICATIONS_FAILURE: 'FETCH_ALL_APPLICATIONS_FAILURE',
};

export default ApplicationTypes;
