const MentorActionTypes = {
  FETCH_MENTORS_START: "FETCH_MENTORS_START",
  FETCH_MENTORS_SUCCESS: "FETCH_MENTORS_SUCCESS",
  FETCH_MENTORS_FAILURE: "FETCH_MENTORS_FAILURE",
  SIGN_UP_MENTOR_START: "SIGN_UP_MENTOR_START",
  SIGN_UP_MENTOR_SUCCESS: "SIGN_UP_MENTOR_SUCCESS",
  SIGN_UP_MENTOR_FAILURE: "SIGN_UP_MENTOR_FAILURE"
};

export default MentorActionTypes;
