const MentorActionTypes = {
  FETCH_MENTORS_START: 'FETCH_MENTORS_START',
  FETCH_MENTORS_SUCCESS: 'FETCH_MENTORS_SUCCESS',
  FETCH_MENTORS_FAILURE: 'FETCH_MENTORS_FAILURE',
  SEND_MENTOR_APPLICATION: 'SEND_MENTOR_APPLICATION',
  FETCH_CATEGORY_OPTIONS_START: 'FETCH_CATEGORY_OPTIONS_START',
  FETCH_CATEGORY_OPTIONS_SUCCESS: 'FETCH_CATEGORY_OPTIONS_SUCCESS',
  FETCH_CATEGORY_OPTIONS_FAILURE: 'FETCH_CATEGORY_OPTIONS_FAILURE',
};

export default MentorActionTypes;
